name: flutter_portfolio
description: my flutter portfolio.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_swiper: ^1.1.6
  chips_choice: ^2.0.1
  provider:
  url_strategy: ^0.2.0
  flutter_spinkit: ^5.1.0
  readmore: ^2.1.0
  font_awesome_flutter: ^9.2.0
  flutter_remix: ^0.0.3
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: CircularSpotify
      fonts:
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-Black.ttf
          weight: 800
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-Book.ttf
          weight: 300
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-BookItalic.ttf
          weight: 300
          style: italic  
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-Light.ttf
          weight: 200
        - asset: assets/fonts/Circular-Spotify/CircularSpotifyTxt-LightItalic.ttf
          weight: 200
          style: italic